# Generated by Django 5.2.4 on 2025-08-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='descrcao',
            new_name='descricao',
        ),
    ]
